config/routes.rb
Rails.application.routes.draw do

  resources :audit_logs, except:[:destroy,:new,:edit] do
    member do
      get :confirm
    end 
  end 
  namespace :admin do
    resources :users
	resources :posts
	resources :admin_users

    root to: "users#index"
  end

  resources :posts do
  	member do 
  		get :approve 
  	end 
  end 
  devise_for :users,skip: [:registrations]
root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
	
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
  enum status: [:pending,:confirmed]
  belongs_to :user
  validates :start_date, presence: true
  validates :status, presence: true
  after_initialize :set_start_date

  private
  def set_start_date
  	self.start_date ||= (Date.today - 6.days)
  end 

end

app/models/post.rb
class Post < ApplicationRecord
	enum status: [:submitted,:approved,:rejected]
	belongs_to :user
	validates :date, presence: true
	validates :rationale, presence: true
	validates :overtime_request, presence: true, numericality: {greater_than: 0.00}
	after_save :update_audit_log

	scope :posts_by, ->(user){where(:user_id => user.id)}

	private

	def update_audit_log
		audit_log = AuditLog.where(:user_id => self.user_id, start_date: (self.date - 7.days..self.date)).last 
		#TODO LOOK OVER THIS CODE
		audit_log.confirmed! if audit_log
	end 

	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :audit_logs
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true,length: {is: 10}
  

  REGEX = /\A[0-9]*\Z/
  validates_format_of :phone_number, with: REGEX
 

  def full_name
	self.first_name + " " + self.last_name
  end 

end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ["AdminUser"]
  end 
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include? current_user.try(:type)        
        redirect_to root_path,notice: "You do not have Administrator Priviledges."
      end 
    end 

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit 
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized


  private 

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

end

app/controllers/audit_logs_controller.rb
class AuditLogsController < ApplicationController
	def index 
		@audit_logs = AuditLog.all.page(params[:page]).per(10)
		authorize(@audit_logs)
	end 

	def show
		@audit_log = AuditLog.find(params[:id])
		authorize(@audit_log)
	end 

	def confirm
		@audit_log = AuditLog.find(params[:id])
		authorize(@audit_log)
		@audit_log.confirmed!
		redirect_to root_path, notice: "Thank you for confirming."
	end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show,:edit,:update,:destroy,:approve]
	
	def index 
		if current_user.is_a?(AdminUser) 
			@posts = Post.all.page(params[:page]).per(10)
		else 
			@posts = Post.posts_by(current_user).page(params[:page]).per(10)
		end 
	end 

	def approve
		authorize(@post)
		@post.approved!
		redirect_to root_path, notice: "Your Post has been approved."

	end 

	def edit
		authorize @post
	end 

	def destroy
		if @post.delete
			redirect_to action: :index, notice: "Your post has been successfully deleted."
		else
			render :index
		end 
	end 

	def update
		if @post.update(post_params)
			redirect_to @post, notice: "Your post has been successfully updated."
		else 
			flash[:alert] = "Something went wrong."			
			render :edit
		end 	
	end 

	def show
		
	end 
	def new
		@post = Post.new
	end 

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to @post,notice: 'Your post was created successfully.'
		else	
			flash.notice = "Something went wrong."	
			render :new
		end 
	end

	private
	 	
	def post_params
		params.require(:post).permit(:date,:rationale,:status,:overtime_request)
	end 
	def set_post
		@post = Post.find(params[:id])
	end 
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def homepage
		if current_user.is_a? AdminUser
			@pending_approvals = Post.where(:status => 'submitted')
			@audit_logs = AuditLog.last(10)
		else
			@audit_logs = AuditLog.where(:user_id => current_user.id, status: 'pending')
		end
		
	end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(path)
		return "active" if current_page?(path)
	end 

	def status_label(status)
		status_generator status
	end 

	private 
	def status_generator status
		case status
		when 'submitted'
			content_tag(:span,status.titleize,class: 'label label-primary')
		when 'approved'
			content_tag(:span,status.titleize,class: 'label label-success')
		when 'rejected'
			content_tag(:span,status.titleize,class: 'label label-danger')
		when 'pending'
			content_tag(:span,status.titleize,class: 'label label-primary')
		when 'confirmed'
			content_tag(:span,status.titleize,class: 'label label-success')
		end	

	end

end

app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	 
end

app/views/audit_logs/_audit_log.html.erb
<tr>
	<th scope="row"><%= audit_log.id %></th>
	<td><%= audit_log.user.full_name%></td>
	<td><%= audit_log.start_date %></td>
	<td><%= audit_log.end_date%></td>
	<td><%= status_label audit_log.status %></td>	
</tr>  

app/views/audit_logs/index.html.erb
<h1>These are the current Audit Logs.</h1>
<br>
<table class="table">
  <thead>
    <tr> 
      <th>Number</th>   
      <th>Employee</th>
      <th>Starting Date:</th>
      <th>Confirmed At:</th>
      <th>Status</th>      
      

    </tr>
  </thead>
  <tbody id='audit_logs'>
  <%= render @audit_logs %>   
   
  </tbody>
  


</table>
 <div id='audit_paginator'>
    <%= paginate @audit_logs,:remote => true %>
  </div>

app/views/audit_logs/index.js.erb
$('#audit_logs').html('<%= escape_javascript render(@audit_logs) %>');
$('#audit_paginator').html('<%= escape_javascript(paginate(@audit_logs, remote: true).to_s) %>');

app/views/audit_logs/show.html.erb
<h2>Log of: <%= @audit_log.user.full_name %></h2>
<div class= 'well'>
	<div>
		<h3>Audit Log for week of: <%= @audit_log.start_date %></h3>
	</div>
	<div>
		<h3>Status: <%= status_label @audit_log.status %></h3>
	</div>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OvertimeApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans" rel="stylesheet"> 
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
			<%= render 'shared/nav.html.erb' %>
	    	<%= yield %>
	    	</div>
		</div>
	</div>
	<%= render partial: 'shared/growl_notifications' %>
	<%= javascript_include_tag 'main.js' %>
  </body>
</html>



			
			

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do |msg| %>
	 	<%= js add_gritter(msg, title: "Overtime APP Notification", sticky: false) %>
	<%end%>
<%end%>
<%= form_for post, class: 'form-horizontal' do |f|%>

<div class='form-group'>
	<%= f.label :overtime_request, class: 'col-sm-2 form-label' %>
	<%= f.text_field :overtime_request, class: 'form-control'%>
</div>

<div class='form-group'>
	<%= f.label :date, class: 'col-sm-2 form-label' %>
	<%= f.date_field :date, class: 'form-control',id: 'datepicker' %>
</div>
<div class='form-group'>
	<%= f.label :rationale, class: 'col-sm-2 form-label' %>
	<%= f.text_area :rationale, class: 'form-control'%>
</div>

<%= render partial: 'status',locals: {f: f} if current_user.type == 'AdminUser' %>

	<%= f.submit "Save",class: 'btn btn-primary btn-block' %>
<% end %>

app/views/posts/_post.html.erb
<tr>
	<th scope="row"><%= post.id %></th>
	<td><%= post.overtime_request %></td>
	<td><%= post.date %></td>
	<td><%= post.user.full_name %></td> 
	<td><%= link_to truncate(post.rationale), post_path(post) %></td>
 	<td><%= status_label post.status %> </td>    
	<td><%= link_to "",edit_post_path(post),class: 'glyphicon glyphicon-pencil glypy', id: "edit_#{post.id}" if policy(post).update? %></td> 
	<td><%= link_to "",post_path(post),method: :delete, class: 'glyphicon glyphicon-trash glypy', id: "destroy_post_#{post.id}",data: {confirm: "Are you sure?"} %></td>  
</tr>  

app/views/posts/_status.html.erb
<div class='form-group'>
	
	<%= f.radio_button :status, 'submitted'%>
	<%= f.label :status, 'Submitted' %>

	
	<%= f.radio_button :status, 'approved'%>
	<%= f.label :status, 'Approved'%>

	
	<%= f.radio_button :status, 'rejected'%>
	<%= f.label :status, 'Rejected' %>	

</div>

app/views/posts/edit.html.erb
<%= render partial: 'form',locals: {post: @post} %>

app/views/posts/index.html.erb
<h1>These are the current Posts.</h1>
<br>
<table class="table">
  <thead>
    <tr>
      
      <th>Post</th>
      <th>Overtime request</th>
      <th>Date</th>
      <th>Name</th>      
      <th>Rationale</th>
      <th>Status</th>

    </tr>
  </thead>
  <tbody id='posts'>
  <%= render @posts %>   
   
  </tbody>
</table>
  <div id='paginator'>
    <%= paginate @posts,:remote => true %>
  </div>

app/views/posts/index.js.erb
$('#posts').html('<%= escape_javascript render(@posts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');

app/views/posts/new.html.erb
<h1>New Request for Overtime.</h1>
<%= render partial: 'form',locals: {post: @post} %>

app/views/posts/show.html.erb
<h2><%= @post.rationale %></h2>
<div class= 'well'>
	<div>
		<h3>Employee: <%= @post.user.full_name %></h3>
	</div>
	<div>
		<h3>Overtime Requested: <%= @post.overtime_request %> hours</h3>
	</div>
	<div>
		<h3>Status: <%= status_label @post.status %></h3>
	</div>
	<div>
		<h3>Date: <%= @post.date %></h3>
	</div>
	
	<div>
		<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-primary' if policy(@post).update? %>
	</div>
</div>

app/views/shared/_audit_log_admin.html.erb
<li id='posts-li' class="<%= active?(audit_logs_path) %>">
	<%= link_to "Audit Logs", audit_logs_path, id: 'audit_logs_nav_bar'%>
</li>

app/views/shared/_growl_notifications.html.erb
<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], title: "Overtime APP Alert", sticky: false) %>
<% elsif flash[:notice]%>
	<%= js add_gritter(flash[:notice], title: "Overtime APP Notice", sticky: false) %>
<% else %>
	<%= js add_gritter(flash[:error], title: "Overtime APP Error", sticky: false) %>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
	<div id="diego" class="navbar-header">
		 
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			 <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
		</button> <a class="navbar-brand" href="/"> <i class="fa fa-calendar-check-o" style='color: black'></i></span> Overtime APP</a>
	</div>
<% if current_user %>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav">
			<li id='home-li' class="<%= active?(root_path) %>">
				<%= link_to "Home", root_path %>				
			</li>
			<li id='posts-li' class="<%= active?(posts_path) %>">
				<%= link_to "Posts", posts_path, id: 'posts_path'%>
			</li>
			<li id='posts-li' class="<%= active?(new_post_path) %>">
				<%= link_to "Request Overtime", new_post_path, id: 'new_post_nav_bar'%>
			</li>
			<%= render 'shared/audit_log_admin' if policy(AuditLog).index? %>			
		</ul>		
		<ul class="nav navbar-nav navbar-right">
			
			<li class="dropdown">
				 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<strong class="caret"></strong></a>
				<ul class="dropdown-menu">
					<li>
						<%= link_to "logout", destroy_user_session_path, method: :delete %>
					</li>
					<% if current_user.type == "AdminUser"%>					
						<li>
							<%= link_to "Admin Dashboard", admin_root_path %>
						</li>
						<li class="divider"></li>
					<% end  %>				
					
				</ul>
			</li>
		</ul>
	</div>
<% end %>
	
</nav>